### ISSUE TITLE
Unable to use --sitemap command even though i uses filiph/linkcheck@2.0.23

### ISSUE THREAD

**Issue by pak-trindaBudi** [filiph/linkcheck#120]
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/122334221/229000772-1b0aead4-8a71-4bb9-be1b-9585d7440d65.png">

**Comment by parlough** [comment]
Hi @pak-trindaBudi , thanks for opening an issue! 

Could you share the full command you entered? 

Also could you point me to where where you learned about a `sitemap` option? As far as I can tell, there isn't a `sitemap` option and I don't see one in the past either. Thanks!

If you're trying to use your sitemap as an entrypoint, the [Many entry points](https://github.com/filiph/linkcheck#many-entry-points) section of the README may help.

**Comment by pak-trindaBudi** [comment]
sorry nevermind. I just want to fetch the sitemap url and doing linkcheck using urls inside sitemap. I'll close this ticket. But i have another issues, i'll create another ticket
