### ISSUE TITLE
linkcheck should ignore robots.txt on localhost

### ISSUE THREAD

**Issue by filiph** [filiph/linkcheck#23]
I'm pretty sure I implemented this feature but @chalin reports that it isn't working (i.e. `linkcheck` conforms to `robots.txt` even on localhost / 127.0.0.1). 

So either I'm remembering wrong, or there's a bug.

**Comment by chalin** [comment]
Ah, no, for all of our sites we're using a non-standard port (e.g., 4000). Should that make a difference? /cc @kwalrath

**Comment by filiph** [comment]
That shouldn't make a difference. But looking at the code now, I remembered wrong. On localhost, we're automatically [not throttling speed](https://github.com/filiph/linkcheck/blob/e80fe4afa68f8981ae356c91cd95b999ce86fcfc/lib/src/server_info.dart#L61), but we do respect `robots.txt`.

Now that I think about it, this might be the right thing to do. Crawling everything on localhost could lead to unexpected issues, especially on dynamic sites. I'm closing this FR, at least for now.
