### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by zeke** [filiph/linkcheck#46]
This tool seems like a good candidate for a [GitHub Actions](https://github.com/features/actions) workflow. Has anyone already looked into setting that up?

cc @filiph

**Comment by filiph** [comment]
I haven't, and I don't have the bandwidth, unfortunately. Would you like to look?

**Comment by filiph** [comment]
To give more details about the resolution of this bug, for posterity. Thanks to @errnesto, linkcheck is now a github action, and I just uploaded it to the marketplace: https://github.com/marketplace/actions/check-links-with-linkcheck. I'm woefully unfamiliar with all this, so please do report problems, as I'm sure there are many.
