### ISSUE TITLE
404 errors on <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="">

### ISSUE THREAD

**Issue by bobatsar** [filiph/linkcheck#49]
I'm trying to check a [mkdocs material](https://squidfunk.github.io/mkdocs-material/) generated documentation.

When checking external links, I get for every page a 
`- (79:8) <link> => https://fonts.gstatic.com (HTTP 404)`

Can this error somehow be suppressed?
I think this is a typical pattern to preconnect to https://fonts.gstatic.com but the URL itself returns a 404!

**Comment by chalin** [comment]
Hi @bobatsar,

> ... Can this error somehow be suppressed?

Yes, instruct linkcheck to skip this URL using a [skip rule](https://github.com/filiph/linkcheck#skipping-urls).

**Comment by bobatsar** [comment]
Yes I saw this also already. I think I can close the issue.
