### ISSUE TITLE
Exception during running crawling "NoSuchMethodError: The getter 'charset' was called on null."

### ISSUE THREAD

**Issue by Phaeton20** [filiph/linkcheck#57]
Complete Error Message:

Crawling: 134Unhandled exception:
NoSuchMethodError: The getter 'charset' was called on null.
Receiver: null
Tried calling: charset
#0      checkPage (package:linkcheck/src/worker/worker.dart:149)
#1      _RootZone.runUnary (dart:async/zone.dart:1379)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:137)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#4      Future._propagateToListeners (dart:async/future_impl.dart:707)
#5      Future._completeWithValue (dart:async/future_impl.dart:522)
#6      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30)
#7      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288)
#8      _fetchHead (package:linkcheck/src/worker/worker.dart:0)
#9      _RootZone.runUnary (dart:async/zone.dart:1379)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707)
#13     Future._completeWithValue (dart:async/future_impl.dart:522)
#14     Future.timeout.<anonymous closure> (dart:async/future_impl.dart:776)
#15     _RootZone.runUnary (dart:async/zone.dart:1379)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707)
#19     Future._completeWithValue (dart:async/future_impl.dart:522)
#20     Future.wait.<anonymous closure> (dart:async/future.dart:400)
#21     _RootZone.runUnary (dart:async/zone.dart:1379)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:137)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#24     Future._propagateToListeners (dart:async/future_impl.dart:707)
#25     Future._completeWithValue (dart:async/future_impl.dart:522)
#26     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#29     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391)
#30     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)
135Unhandled exception:
NoSuchMethodError: The getter 'charset' was called on null.
Receiver: null
Tried calling: charset
#0      checkPage (package:linkcheck/src/worker/worker.dart:149)
#1      _RootZone.runUnary (dart:async/zone.dart:1379)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:137)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#4      Future._propagateToListeners (dart:async/future_impl.dart:707)
#5      Future._completeWithValue (dart:async/future_impl.dart:522)
#6      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30)
#7      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288)
#8      _fetchHead (package:linkcheck/src/worker/worker.dart:0)
#9      _RootZone.runUnary (dart:async/zone.dart:1379)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707)
#13     Future._completeWithValue (dart:async/future_impl.dart:522)
#14     Future.timeout.<anonymous closure> (dart:async/future_impl.dart:776)
#15     _RootZone.runUnary (dart:async/zone.dart:1379)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707)
#19     Future._completeWithValue (dart:async/future_impl.dart:522)
#20     Future.wait.<anonymous closure> (dart:async/future.dart:400)
#21     _RootZone.runUnary (dart:async/zone.dart:1379)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:137)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678)
#24     Future._propagateToListeners (dart:async/future_impl.dart:707)
#25     Future._completeWithValue (dart:async/future_impl.dart:522)
#26     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#29     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391)
#30     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)
Done crawling.

**Comment by filiph** [comment]
Ooof, this took way longer than I anticipated, but it's finally fixed in version `2.0.15`. If things don't work as expected, please run linkcheck with `--verbose` and paste the output here. Thanks for the patience!
