### ISSUE TITLE
Are the HTML-pages cached?

### ISSUE THREAD

**Issue by cyfyrifilefe** [filiph/linkcheck#71]
Hello, thanks for your work.

I have some questions:
1. Are  HTML-pages cached.
2. If yes, where?
3. If not, what code to add and where for caching them? 

Cheers,
Lyric ;-)

**Comment by filiph** [comment]
Hi!

The pages are not cached. It would be really hard to figure out when to invalidate the cache. The `linkcheck` tool kind of assumes now that you're running it locally on your whole site, trying to check all of it. It should be fast enough that we don't need caching.

What's your use case for caching, exactly?

The code for caching would probably live somewhere around https://github.com/filiph/linkcheck/blob/master/lib/src/worker/pool.dart.

**Comment by cyfyrifilefe** [comment]
Hi Filiph,

thank you for your response. 

I'd like to add  some spell-checking on the downloaded HTML pages. Since I don't know Dart. I thought that maybe the pages were cached somewhere.

**Comment by filiph** [comment]
Ah, got it, thanks for the explanation! 

> I'd like to add some spell-checking on the downloaded HTML pages.

That would be hard to include in `linkcheck` without making things slower & more complicated. For spell checking, I think `wget` or `curl` is probably a better option.

I'm closing this, at least for now.
