### ISSUE TITLE
github actions: Unable to pass -e

### ISSUE THREAD

**Issue by liskin** [filiph/linkcheck#72]
It's not possible to pass both `-e` and a URI as arguments when using this as a github actions, as  https://github.com/filiph/linkcheck/blob/5090e8c7080c17056e12e318b5c546c53849dc75/action.yml#L16 passes it all as a single argument with spaces. Unfortunately https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsargs looks like this can't be done easily. :-/

I worked it around by forking and adding the flag manually, but that's a terrible hack: https://github.com/liskin/linkcheck/commit/2d34f2f6ab3c7553a319081064ae2b2619744777

**Comment by filiph** [comment]
Damn. One of these days I'll take a closer look at GitHub Actions. I'm guessing the best way would be to maintain the list of options in `action.yml`?

To be clear, I won't have time to actively look into this in the foreseeable future. If there's anyone out there who has the time & motivation to fix it, please send a PR.
