### ISSUE TITLE
Question : what's up with the linux binary having a .exe extension ? 

### ISSUE THREAD

**Issue by AnnoyingTechnology** [filiph/linkcheck#78]
First time seeing that, it seems confusing (I almost thought there was no Linux binary available at first). 
Maybe there is a reason and I'm missing something ?

![Screenshot from 2021-05-26 08-33-08](https://user-images.githubusercontent.com/5336824/119613404-4b24a380-bdfd-11eb-97da-b72dafcd95d6.png)

**Comment by filiph** [comment]
Yeah, it's weird. I can't remember why I did it this way, but I swear there was some reason.

Anyway, I think this is now moot thanks to https://github.com/filiph/linkcheck/issues/77.

**Comment by shittyfollower** [comment]
Hey, so how do I run it if I put it into a directory in Linux? Thanks in advance. 
Failing that, how would I clone from Github and run that way?

**Comment by filiph** [comment]
Hi, you should be able to run it normally. Let's say you donwloaded a file like `linkcheck-linux.exe`.

You'd then do:

```text
$ ./linkcheck-linux.exe
```

You _might_ need to do `chmod +x linkcheck-linux.exe` first, but I think the binary comes as an executable already. Let me know if you hit a snag.

**Comment by shittyfollower** [comment]
Ok thanks Filip I will give it a shot
